[theme]
# Primary accent color for interactive elements.
primaryColor = "#3d95f9"


# Background color for the main content area.
backgroundColor = "#c5c8c6"


# Background color used for the sidebar and most interactive widgets.
secondaryBackgroundColor = "#99cdfc"


# Color used for almost all text.
textColor = "#333333"

